---
- name: Register CouchDB version
  command: "couch-config --version|head -1"
  register: couchdb_version
  ignore_errors: true
  
- name: unarchive
  unarchive: src=http://www.us.apache.org/dist/couchdb/source/1.6.1/apache-couchdb-1.6.1.tar.gz dest=/tmp/ copy=no
  when: "{{ couchdb_version.stdout_lines }} != 'couch-config - Apache CouchDB configuration helper 1.6.1'"
  
- name: Configure
  command: ./configure --disable-docs --with-erlang=/usr/lib64/erlang/usr/include/
  args:
    chdir: /tmp/apache-couchdb-1.6.1
  when: "{{ couchdb_version.stdout_lines }} != 'couch-config - Apache CouchDB configuration helper 1.6.1'"

- name: make
  command: make
  args:
    chdir: /tmp/apache-couchdb-1.6.1
  when: "{{ couchdb_version.stdout_lines }} != 'couch-config - Apache CouchDB configuration helper 1.6.1'"

- name: Create group
  become: yes
  group: name=couchdb state=present

- name: Create folders
  become: yes
  shell: >-
    mkdir -p /var/{run,lib,log}/couchdb;
    mkdir -p /usr/local/var/lib;

- name: Create user
  become: yes
  user: name=couchdb comment="Couchdb user" group=couchdb groups=couchdb shell="/sbin/nologin" home='/usr/local/var/lib/couchdb/' createhome=yes

- name: Install
  become: yes
  command: make install
  args:
    chdir: /tmp/apache-couchdb-1.6.1
  when: "{{ couchdb_version.stdout_lines }} != 'couch-config - Apache CouchDB configuration helper 1.6.1'"

- name: Permissions
  become: yes
  shell: >-
    chown -R couchdb: /var/lib/couchdb /var/log/couchdb;
    chown -R couchdb: /usr/local/var/{lib,log,run}/couchdb /usr/local/etc/couchdb /var/run/couchdb;
    chmod 0770 /usr/local/var/{lib,log,run}/couchdb/;
    chmod 664 /usr/local/etc/couchdb/*.ini;
    chmod 775 /usr/local/etc/couchdb/*.d;

- name: Copy service
  become: yes
  copy: src=couchdb.service dest=/etc/systemd/system/couchdb.service

- name: Start couchdb on boot
  become: True
  service: name=couchdb state=started enabled=yes

- name: Wait for CouchDB to be available
  pause: seconds=10

- name: Configure couchdb
  shell: >
    /usr/bin/curl http://localhost:5984/_config/httpd/socket_options -XPUT -d '"[{recbuf, 262144}, {sndbuf, 262144}, {nodelay, true}]"'