---
#users:
#  - name: user1
#    key: "ssh public key to deploy"
#  - name: user2
#    key: "ssh public key to deploy"

packages:
  - bash
  - telnet
  - tmux
  - vim
  - git
  - ntp
  - openssl
  - openssl-devel
  - gcc
  - gcc-c++
  - bzip2
  - cmake
  - autoconf
  - automake
  - libtool
  - texinfo
  - psmisc

epel_packages:
  - czmq-devel
