---
- name: Pull repo
  git:
    dest: /tmp
    accept_hostkey: yes
    version: '2.6.1'
    repo: 'git://github.com/rebar/rebar.git'
    force: yes
    depth: 1

- name: Bootstrap
  command: ./bootstrap
  args:
    chdir: /tmp/rebar/

- name: Copy binary into place
  command: cp rebar /usr/local/bin/

- name: Clean up
  file: path=/tmp/rebar state=absent recurse=yes
