- name: Refresh daemons
  become: true
  command: 'systemctl daemon-reload'

- name: reload nginx
  become: true
  service: name={{ item.value.system_name }} state=reloaded
  with_dict: services_nginx

- name: restart nginx
  become: True
  service: name={{ item.value.system_name }} state=restarted
  with_dict: services_nginx

