---
#
#- name: Install prerequisits
#  yum: name=ncurses-devel.x86_64 state=latest

#- name: Extract
#  unarchive: src=http://www.erlang.org/download/otp_src_{{ erlang_version }}.tar.gz dest=/tmp/ copy=yes

#- name: Build
#  command: make
#  args:
#    chdir: /tmp/otp_src_{{ erlang_version }}/

#- name: Install
#  become: YES
#  command: make install
#  args:
#    chdir: /tmp/otp_src_{{ erlang_version }}/

#- name: Clean up
#  become: YES
#  file: path=/tmp/otp_src_{{ erlang_version }}/ state=absent recurse=yes

- name: Install
  become: yes
  yum: name=erlang state=latest

