---
- name: Install nginx
  become: yes
  yum: name=nginx state=present

- name: Generate services definition
  become: yes
  template: src=nginx.service.j2 dest=/etc/systemd/system/{{ item.value.system_name}}.service mode=0644
  with_dict: "{{ services_nginx }}"

- name: Customize nginx default configuration
  become: yes
  template: src=nginx.conf.j2 dest=/etc/nginx/{{ item.value.system_name}}.conf owner=root group=root mode=0644
  notify: restart nginx
  with_dict: "{{ services_nginx }}"

- name: Create error template folder
  become: yes
  file: path=/etc/nginx/errors/ state=directory owner=root group=root mode=0755

- name: Copy error 404 template
  become: yes
  copy: src=404.html dest=/etc/nginx/errors/404.html owner=root group=root mode=0644

- name: Copy error 50x template
  become: yes
  copy: src=50x.html dest=/etc/nginx/errors/50x.html owner=root group=root mode=0644

- name: Start nginx on boot
  become: yes
  service: name={{ item.value.system_name }} state=started enabled=yes
  with_dict: "{{ services_nginx }}"

