---
- name: Sanity
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Stop there if trying to deploy in dev
      fail: msg="Stopping here, do not deploy to a shared folder! It is already up to date (since it's shared)."
      when: development == true

- name: Deploy
  hosts: all
  gather_facts: true
  vars_files:
    - vars/services.yml
    - vars/main.yml

  roles:
    - nodejs
    - assets
    - potato_bin
