- name: Vagrant Basic role
  become: True
  hosts: all
  gather_facts: False

  roles:
    - base

  tasks:
    - name: Add vagrant user to users and potato groups
      user: name=vagrant groups="users,potato" append=yes
      notify:
        - Work around permission issue for vagrant

  handlers:
    - name: Work around permission issue for vagrant
      file: path=/usr/local/src state=directory owner=root group=users mode=0777

- name: Provision
  hosts: all
  gather_facts: False

  vars_files:
    - vars/main.yml
    - vars/services.yml

  roles:
    - nginx
    - memcached
    - couchdb
    - rabbitmq
    - solr
    - clisp-app
    - haproxy
    - hardening # To be run last since the vagrant user will be deleted