---
# Default deployment branch is master,
# this can easily be otherwriten from the command line with the -e argument

deployment_branch: 'master'

# Variable precedence:
#* extra vars (-e in the command line) always win
#* then comes connection variables defined in inventory (ansible_ssh_user, etc)
#* then comes "most everything else" (command line switches, vars in play, included vars, role vars, etc)
#* then comes the rest of the variables defined in inventory
#* then comes facts discovered about a system
#* then "role defaults", which are the most "defaulty" and lose in priority to everything.

# https://docs.ansible.com/playbooks_variables.html