---

# Mozilla tracks spidermonkey on HG
# Mozilla read-only git repo tags are outdated when compared to HG tags
# I don't want to install another version control tool
# Using HG download gz function instead
#- name: Download source
#  get_url: url=http://hg.mozilla.org/mozilla-central/archive/{{ spidermonkey_commitid }}.tar.gz dest={{ git_project_root.stdout }}/cache
#  delegate_to: 127.0.0.1

#- name: Copy to server
#  copy: src={{ git_project_root.stdout }}/cache/{{ spidermonkey_commitid }}.tar.gz dest=/tmp/

#- name: Extract
#  unarchive: src={{ git_project_root.stdout }}/cache/{{ spidermonkey_commitid }}.tar.gz dest=/tmp/ copy=yes

#- name: Install autoconf 2.13
#  yum: name=autoconf213 state=latest

#- name: Build
#  shell: >
#    cd /tmp/{{ spidermonkey_commitid }}/js/ &&
#    autoconf-2.13 &&
#    mkdir build_OPT.OBJ &&
#    cd build_OPT.OBJ &&
#    ../configure &&
#    make
#    make install

#- name: Install
#  become: YES
#  command: make install
#  args:
#    chdir: /tmp/{{ spidermonkey_commitid }}/js/build_OPT.OBJ/

#- name: Cleanup
#  become: YES
#  file: path=/tmp//{{ spidermonkey_commitid }} state=absent

- name: Install
  become: yes
  yum: name=js-devel state=latest
