---
- name: Installed
  command:  convert -version | head -1 || true
  register: imagemagick_version
  ignore_errors: True

- name: Checkout git
  become: true
  git:
    dest: "{{ workspace }}/ImageMagick"
    version: '{{ imagemagick_target_version }}'
    accept_hostkey: yes
    repo: 'https://github.com/ImageMagick/ImageMagick.git'
    force: yes
    depth: 1

- name: Compile
  become: true
  command: "{{ item }} chdir={{ workspace }}/ImageMagick/"
  with_items:
    - ./configure
    - make
  when: "'{{ imagemagick_target_version  }}' not in '{{ imagemagick_version.stdout | default([]) }}'"


- name: Install
  become: true
  command: "{{ item }} chdir={{ workspace }}/ImageMagick/"
  with_items:
    - make install
    - ldconfig /usr/local/lib
  when: "'{{ imagemagick_target_version  }}' not in '{{ imagemagick_version.stdout | default([]) }}'"

