---
quicklisp_dist: '2016-04-21'

commons:
  db_hostname: 'localhost'
  db_port: 5984
  db_name: &db_name 'potato'
  solr_path_location: 'http://localhost:8983/solr/potato'
  smtp_server_host: 'smtp.mandrillapp.com'
  smtp_server_port: 587
  application_path: '/potato/'

services:
  potato:
    system_name: &system_name 'potato'
    service: 'potato'
    description: 'Potato site'
    listen_port: &listen_port_potato 8080
    swank_port: &swank 4006
  potato-index:
    service: 'index'
    system_name: 'potato-index'
    description: 'Potato Index'
    swank_port: &swank_index 4007
  potato-state:
    service: 'state-server'
    system_name: 'potato-state'
    description: 'Potato state'
    swank_port: &swank_state 4008
  potato-content-processor:
    service: 'content-processor'
    system_name: 'potato-content-processor'
    description: 'Potato content processor'
    swank_port: &swank_content_processor 4010
  potato-email-updates:
    service: 'email-updates'
    system_name: 'potato-email-updates'
    description: 'Potato email updates'
    swank_port: &swank_email_updates 4011

services_nginx:
  nginx:
    system_name: 'nginx'
    description: 'NGINX Potato site'
    listening_port: &listening_port_nginx 8180
    potato_port: *listen_port_potato
    potato_path: *system_name

port_forwards:
  - name: "swank"
    remote: *swank
    local: *swank
  - name: "swank_index"
    remote: *swank_index
    local: *swank_index
  - name: "swank_state"
    remote: *swank_state
    local: *swank_state
  - name: "swank_content_processor"
    remote: *swank_content_processor
    local: *swank_content_processor
  - name: "swank_email_updates"
    remote: *swank_email_updates
    local: *swank_email_updates
  - name: "nginx"
    remote: *listening_port_nginx
    local: *listening_port_nginx
  - name: "RabbitMQ"
    remote: 15672
    local: 15672