---
quicklisp_dist: '2016-04-21'

commons:
  db_hostname: 'localhost'
  db_port: 5984
  db_name: &db_name 'potato'
  solr_path_location: 'http://localhost:8983/solr/potato'
  smtp_server_host: 'smtp.mandrillapp.com'
  smtp_server_port: 587
  application_path: '/potato/current/'

services:
  potato-a:
    system_name: &system_name_a 'potato-a'
    service: 'potato'
    description: 'Potato site a'
    listen_port: &listen_port_potato_a 8080
    swank_port: &swank_a 4005
    haproxy_name: &haproxy_potato_a 'potato_a'
    websocket_listen_port: &websocket_listen_port_a 8090
  potato-b:
    system_name: &system_name_b 'potato-b'
    service: 'potato'
    description: 'Potato site b'
    listen_port: &listen_port_potato_b 8081
    swank_port: &swank_b 4006
    haproxy_name: &haproxy_potato_b 'potato_b'
    websocket_listen_port: &websocket_listen_port_b 8091
  potato-index:
    service: 'index'
    system_name: 'potato-index'
    description: 'Potato Index'
    swank_port: &swank_index 4007
  potato-state:
    service: 'state-server'
    system_name: 'potato-state'
    description: 'Potato state'
    swank_port: &swank_state 4008
  potato-content-processor:
    service: 'content-processor'
    system_name: 'potato-content-processor'
    description: 'Potato content processor'
    swank_port: &swank_content_processor 4010
  potato-email-updates:
    service: 'email-updates'
    system_name: 'potato-email-updates'
    description: 'Potato email updates'
    swank_port: &swank_email_updates 4011

services_nginx:
  nginx_a:
    system_name: 'nginx-a'
    description: 'NGINX Potato site a'
    listening_port: &listening_port_nginx_a 8180
    potato_port: *listen_port_potato_a
    potato_path: *system_name_a
  nginx_b:
    system_name: 'nginx-b'
    description: 'NGINX Potato site b'
    listening_port: &listening_port_nginx_b 8190
    potato_port: *listen_port_potato_b
    potato_path: *system_name_b

services_haproxy:
  system_name: 'haproxy'
  description: 'HAProxy'
  listening_port: 80

config_haproxy:
  -
    name: *haproxy_potato_a
    port: *listening_port_nginx_a
    host: '127.0.0.1'
    ws: *websocket_listen_port_a
  -
    name: *haproxy_potato_b
    port: *listening_port_nginx_b
    host: '127.0.0.1'
    ws: *websocket_listen_port_b

port_forwards:
  - name: "swank_a"
    remote: *swank_a
    local: *swank_a
  - name: "swank_b"
    remote: *swank_b
    local: *swank_b
  - name: "swank_index"
    remote: *swank_index
    local: *swank_index
  - name: "swank_state"
    remote: *swank_state
    local: *swank_state
  - name: "swank_content_processor"
    remote: *swank_content_processor
    local: *swank_content_processor
  - name: "swank_email_updates"
    remote: *swank_email_updates
    local: *swank_email_updates
  - name: "nginx_a"
    remote: *listening_port_nginx_a
    local: *listening_port_nginx_a
  - name: "nginx_b"
    remote: *listening_port_nginx_b
    local: *listening_port_nginx_b
  - name: "haproxy_admin"
    remote: 9000
    local: 9000
  - name: "RabbitMQ"
    remote: 15672
    local: 15672