---
# file: host_vars/potato-vagrant-staging.yml
hostname: 'potato-vagrant-staging'
production: false
development: false

smtp_username: 'potato'
smtp_password: 'Sj1plr8OBAT67sO_Zr7uHw'

potato_sender_address: 'Potato Login (staging) <support@potato.network>'

external_listen_address: 'localhost'
external_listen_port: 8080

s3_directory: 'staging'
s3_bucket: 'the-potato'
s3_secret_key: 'VwtLRnXU7jlwJPkCaMTayqgquit20COZSa8KHzrM'
s3_access_key: 'AKIAJO7UTZJSDI76LZLQ'
s3_browser_secret_key: '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'
s3_browser_access_key: 'AKIAJ6RGKSNAMVZ32IHQ'
s3_endpoint: 'the-potato.s3.amazonaws.com'

#  sso_keytab: 'potato.env.keytab'
youtube_key: 'AIzaSyBU9B5x9X4DHPnEARVYLZ9eBJ-lv7XDezI'

haproxy_frontend_custom:
  - 'bind *:443 ssl crt /etc/ssl/haproxy.pem'
  - 'redirect scheme https if !{ ssl_fc }'