---
- name: Set a sane locale
  copy: src=environment dest=/etc/environment owner=root group=root mode=0644

- name: Configure Yum to use IPv4 hostnames by default
  lineinfile:
    dest=/etc/yum.conf
    line="ip_resolve=4"
    insertafter=EOF

- name: Install common packages
  yum: pkg={{ item }} state=latest
  with_items: "{{ packages }}"

- name: NTP daemon
  service: name=ntpd state=started enabled=yes

- name: Disable firewalld daemon
  service: name=firewalld state=stopped enabled=no

- name: Add latest EPEL repository
  copy: src=epel-bootstrap.repo dest=/etc/yum.repos.d/
        mode=0644 owner=root group=root

- name: Set hostname
  hostname: name={{ hostname }}

- name: Install latest EPEL repository
  yum: name=epel-release enablerepo=epel-bootstrap state=present

- name: Enable EPEL repository
  ini_file: dest=/etc/yum.repos.d/epel.repo section=epel option=enabled value=1

- name: Install packages from EPEL
  yum: pkg={{ item }} state=latest
  with_items: "{{ epel_packages }}"

- name: sudo group
  group: name=sudo system=yes

- name: potato group
  group: name=potato system=yes

- name: Create named users
  user: name={{ item.name }} group=users groups="sudo,potato" shell="/bin/bash"
  with_items: "{{ users | default([]) }}"
  when: users is defined
  
- name: Add SSH keys to named users
  authorized_key: user={{ item.name }} key="{{ item.key }}"
  with_items: "{{ users | default([]) }}"
  when: users is defined

- name: Sudoers don't need a password
  lineinfile: "dest=/etc/sudoers regexp='^%sudo' line='%sudo ALL=(ALL) NOPASSWD:ALL' validate='/usr/sbin/visudo -cf %s'"

- name: Sudoers don't need TTY
  lineinfile: "dest=/etc/sudoers regexp='^Defaults.*requiretty' line='#Defaults requiretty' validate='/usr/sbin/visudo -cf %s'"

- name: Sudoers have their SSH agent forwarded
  copy: src=sudo_forward_ssh_agent dest=/etc/sudoers.d/sudo_forward_ssh_agent
        mode=0660 owner=root group=root
        validate='/usr/sbin/visudo -cf %s'

- name: Copy known_hosts file to users
  copy: src=known_hosts dest=/home/{{ item.name }}/.ssh/known_hosts force=no owner={{ item.name }} mode="u+rw,g-rwx,o-rwx"
  with_items: "{{ users | default([]) }}"
  when: users is defined
  
- name: Create the potato user
  user: name=potato comment="The Potato" uid=1214 group=potato groups=users
        shell="/sbin/nologin" home="/potato" createhome=no

- name: Add potato user to sudoer
  user: name=potato comment="The Potato" groups="potato,sudo" shell="/sbin/nologin" home="/potato" createhome=no
  when: "{{ development }}"

- name: Create the /potato directory(s)
  file: path=/potato state=directory owner=potato group=potato mode=0775
  ignore_errors: yes

- name: Copy bashrc
  copy: src=bashrc dest=/potato/.bashrc mode=0750 owner=potato
  when: "{{ development }} == false"

- name: Make the /usr/local/src writable
  file: path=/usr/local/src state=directory owner=root group=users mode=0770
